### ISSUE TITLE
zk-citar documentation?

### ISSUE THREAD

**Issue by bdarcus** [localauthor/zk#54]
@localauthor - I finally started to add a related packages sections to the citar readme, and was planning to include ~zk-citar~. But there's no documentations on it. Could you add something brief; even just explicitly mention it?

**Comment by maasdorp** [comment]
What is the status of zk-citar? It is not on elpa, but it still lives here on github.

**Comment by localauthor** [comment]
zk-citar is one of a few small zk-related packages that I never submitted to MELPA, but still maintain in the zk repo. (zk-consult, zk-link-hint and zk-org-linke are the others.) I suppose if there is interest, I could submit them. Have you given zk-citar (or the others) a try?

**Comment by maasdorp** [comment]
I use zk and I use citar. However, my citar usage is very basic since I recently switched away from org-mode (and using citar as org-cite processor) for writing to using quarto markdown.
In zk I always made my literature notes the way I make regular notes, I just add the citekey by hand in the title. I want to give zk-citar a spin and use the citar note features and the title template. Let me download zk-citar and see whether I get it to work. I will report back.

**Comment by kchousos** [comment]
Is there a way to control the body of the new note created with zk-citar? Something like a template for the file contents, besides the title?
