### ISSUE TITLE
zk-new-note with / in title tries to create a directory

### ISSUE THREAD

**Issue by louis77** [localauthor/zk#55]
I.e. when I give the following title:

`Meeting with ABC/John Doe`

zk tried to create a directory `202212201234 Meeting with ABC` with a file `John Doe.org`.

I think zk needs to normalize the note title.

**Comment by localauthor** [comment]
I've just forced myself not to use certain characters when creating new notes ;)

Would a good solution be to add some code into `zk-new-note`, to catch any disallowed characters and raise an error, or simply replace them?

This would still not allow you to have those disallowed characters in the title, since zk always reads the title from the file itself, not from the header (for the purposes of `zk-insert-link`, for example).

What do you think?
